build: off

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\\Miniconda-x64

    - PYTHON_VERSION: 3.6
      MINICONDA: C:\\Miniconda36-x64

platform:
    - x64

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib setuptools pip cython>=0.20 pytest gsl"
  - activate test-environment

  # Environment variables for GSL linking
  - set INCLUDE=CONDA_PREFIX\Library\include;%INCLUDE%
  - set LIB=CONDA_PREFIX\Library\include;%LIB%
  - set LIBPATH=CONDA_PREFIX\Library\include;%LIBPATH%

  - python setup.py build_ext --coverage --single_ext --inplace
  - python setup.py develop --single_ext

test_script:
  - pytest -v tests\test_potential.py
