language: python
python:
  - "2.7"
env:
  - CC= gcc
  - CC= clang
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install libgsl0-dev
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
# command to install dependencies
install:
 - pip install coveralls
 - pip install nose-cov
 - python setup.py develop -c $CC
script:
 - nosetests -v -w nose/ --with-cov --cov galpy
after_success:
 coveralls
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
