language: python
python:
  - "2.7"
#env: #Doesn't seem to work terribly well
#  - CC=gcc
#  - CC=clang LDSHARED=clang
env: #split tests into two
   - NOSE_IGNORE_FILES='test_qdf.py|test_diskdf.py|test_orbit.py'
   - NOSE_IGNORE_FILES='^((?!test_orbit).)*$'
   - NOSE_IGNORE_FILES='^((?!test_diskdf).)*$'
   - NOSE_IGNORE_FILES='^((?!test_qdf).)*$'
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install libgsl0-dev
 - pip uninstall -y numpy #uninstall numpy from virtualenv
 - sudo apt-get install -qq python-scipy python-matplotlib
 - sudo dpkg -r --force-depends python-numpy #because this is 1.6.1
 - pip install numpy>=1.7
 - export DISPLAY=:99.0 #For plotting tests, courtesy Ryan Varley
 - sh -e /etc/init.d/xvfb start $For plotting tests
# command to install dependencies
install:
 - pip install gcovr
 - pip install coveralls
 - pip install nose-cov
 - pip install coveralls-merge
 - python setup.py develop
 - "gem install coveralls-lcov"
script:
 - nosetests -v -w nose/ --with-cov --cov galpy --cov-config .coveragerc_travis
after_success:
 # Download lcov output 
 - wget http://sns.ias.edu/~bovy/galpy_lcov/coverage.info -O coverage.info
 # combine, generate json, and upload
 - coveralls-lcov -v -n coverage.info > coverage.c.json
 - coveralls-merge coverage.c.json
# - coveralls
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
