language: python
python:
  - "2.7"
#env: #Doesn't seem to work terribly well
#  - CC=gcc
#  - CC=clang LDSHARED=clang
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install libgsl0-dev
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
 - export DISPLAY=:99.0 #For plotting tests, courtesy Ryan Varley
 - sh -e /etc/init.d/xvfb start $For plotting tests
# command to install dependencies
install:
 - pip install gcovr
 - pip install coveralls
 - pip install nose-cov
 - python setup.py develop
script:
 - nosetests -v -w nose/ --with-cov --cov galpy --cov-config .coveragerc_travis
after_success:
 - coveralls
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
