language: python
python:
  - "2.7"
#env: #Doesn't seem to work terribly well
#  - CC=gcc
#  - CC=clang LDSHARED=clang
env: #split tests into two
   - NOSE_IGNORE_FILES='test_qdf.py|test_diskdf.py|test_orbit.py|test_coords.py'
   - NOSE_IGNORE_FILES='^((?!test_orbit).)*$'
   - NOSE_IGNORE_FILES='^((?!test_diskdf).)*$'
   - NOSE_IGNORE_FILES='^((?!test_qdf).)*$'
   - NOSE_IGNORE_FILES='^((?!test_coords).)*$'
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install libgsl0-dev
 - sudo apt-get -qq install lcov
# - pip uninstall -y numpy #uninstall numpy from virtualenv
 - sudo apt-get install -qq python-scipy python-matplotlib
# - sudo dpkg -r --force-depends python-numpy #because this is 1.6.1
# - pip install numpy>=1.7
 - export DISPLAY=:99.0 #For plotting tests, courtesy Ryan Varley
 - sh -e /etc/init.d/xvfb start $For plotting tests
# command to install dependencies
install:
 - pip install coveralls
 - pip install nose-cov
 - pip install -U requests
 - pip install git+git://github.com/wiredfool/coveralls-merge.git#egg=coveralls-merge
 - gem install coveralls-lcov
 - python setup.py build_ext --coverage --single_ext --inplace
 - python setup.py develop --single_ext
script:
 - lcov --capture --directory build/temp.linux-x86_64-2.7/galpy/ --output-file coverage.info --initial
 - nosetests -v -w nose/ --with-cov --cov galpy --cov-config .coveragerc_travis
after_success:
 # Generate lcov output 
 - ls build
 - ls build/temp.linux-x86_64-2.7/galpy/potential_src/potential_c_ext/
 - lcov --capture --directory build/temp.linux-x86_64-2.7/galpy/ --output-file coverage.info
 # combine, generate json, and upload
 - coveralls-lcov -v -n coverage.info > coverage.c.json
 - coveralls-merge coverage.c.json
# - coveralls
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
