language: python
python:
  - "2.7"
compiler:
  - clang
  - gcc
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install libgsl0-dev
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
# command to install dependencies
install:
 - python setup.py install
script:
 - nosetests -v -w nose/
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
