name: Build pyodide/wasm wheels

on:
  push:
    branches:
      - main
      - add-pyodide-wheels
    paths-ignore:
      - 'doc/**'

jobs:
  build:
    name: Build pyodide/wasm wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jobovy/pyodide-buildpackage-action@main
        with:
          pyodide-tag: main
          meta-yaml-path: .github/pyodide_meta.yaml
      - name: Rename wheels to 'latest' version
        run: |
          GALPY_VERSION="$(awk '/^current_version/{print $NF}' .bumpversion.cfg)"
          for f in wheelhouse/*$GALPY_VERSION*; do sudo mv -i -- "$f" "${f//$GALPY_VERSION/latest}"; done
      - uses: actions/upload-artifact@v2-preview
        with:
          name: galpy-wheel-pyodide
          path: wheelhouse/*.whl
      # Upload to AWS S3
      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --exclude "*macos*" --exclude "*win*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: wheelhouse
          DEST_DIR: wheelhouse
