name: Build pyodide/wasm wheels

on:
  push:
    paths:
      - '.github/workflows/build_pyodide_wheels_outoftree.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.2
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.14
      - run: pip install pyodide-build==0.21.0
      - name: Build wheel
        run: |
          # From https://github.com/pyodide/pyodide/issues/3002#issuecomment-1248513970
          # Set up libs dir and pkg config
          mkdir .libs
          export LIBDIR=`pwd`/.libs
          export PKG_CONFIG_PATH=`pwd`/.libs/lib/pkgconfig

          # Build gsl
          wget https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz
          tar -xvzf gsl-2.7.tar.gz
          cd gsl-2.7
          source $EMSDK/emsdk_env.sh
          emconfigure ./configure \
              CFLAGS="-fPIC" \
              --prefix=$LIBDIR \
              --disable-dependency-tracking \
              --disable-shared
          emmake make -j 3
          emmake make install

          # Build galpy
          cd ..
          CFLAGS=`pkg-config --cflags-only-I --dont-define-prefix gsl` \
          LDFLAGS=`pkg-config --libs-only-L --dont-define-prefix gsl` \
          pyodide build
      - uses: actions/upload-artifact@v3
        with:
          name: galpy-wheel-pyodide
          path: '*.whl'
