name: Build manylinux wheels, upload to PyPI upon release

# Update on every push or PR to main (except when only docs) and upon releases
on:
  push:
    branches:    
      - main
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
  release:
    types: [created]

jobs:
  build:
    name: Build manylinux wheels, upload to PyPI upon release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build manylinux2014_x86_64 wheels
        uses: ./.github/workflows/actions/manylinux2014_x86_64/
      - name: Rename wheels to 'latest' version
        if: github.event_name != 'release' || github.event.action != 'created'
        run: |
          GALPY_VERSION="$(awk '/^current_version/{print $NF}' .bumpversion.cfg)"
          for f in wheelhouse/*$GALPY_VERSION*; do mv -i -- "$f" "${f//$GALPY_VERSION/latest}"; done
      - uses: actions/upload-artifact@v2-preview
        with:
          name: galpy-wheels-manylinux
          path: wheelhouse/*manylinux*.whl
      # Upload to PyPI if this is a release
      - name: Publish distribution to PyPI
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_token }}
          packages_dir: wheelhouse/
