name: 'Close stale issues'
on:
  schedule:
    - cron: '0 20 * * 1'

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If the issue has been resolved since the last activity, please close the issue. Thank you for your contributions.'
          stale-issue-label: 'wontfix'
          exempt-issue-labels: 'pinned,security'
